name: oggm_env
channels:
  - oggm
  - conda-forge
dependencies:
  - python=3.6
  - oggm-deps
  - numpy>=1.15.1
  - rasterio>=1.0
  - ipython
  - ipympl
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::holoviews
  - pyviz::panel
  - pip:
    - git+https://github.com/OGGM/oggm.git
